package com.katsuna.commons.entities;

public enum ColorProfileKey {
    MAIN_COLOR_VERY_LIGHT,
    MAIN_COLOR_LIGHT,
    MAIN_COLOR_MEDIUM,
    MAIN_COLOR_DARK,
    POP_UP_COLOR,
    ACCENT1_COLOR,
    ACCENT2_COLOR,
    ACCENT3_COLOR,
    DENIAL_COLOR,
    PRIMARY_TEXT_OPACITY,
    SECONDARY_TEXT_OPACITY,
    DISABLED_TEXT_OPACITY,
    DIVIDERS_OPACITY,
    ACTIVE_ICONS_OPACITY,
    INACTIVE_ICONS_OPACITY
}
